name: Build and deploy Node.js app to Azure Web App - almuhammadi

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install deps
        run: npm ci || npm install

      # CRA warnings (like react-hooks/exhaustive-deps) won't fail CI
      - name: Build (don’t fail on warnings)
        env:
          CI: false
          ESLINT_NO_DEV_ERRORS: true
        run: npm run build --if-present

      # Optional: run tests without hanging CI (won’t fail deploy if they warn)
      # - name: Test (CI-friendly)
      #   run: npm test -- --watchAll=false

      # Upload only what Azure needs; include build/ so it can be served
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            build
            package.json
            package-lock.json
            pnpm-lock.yaml
            yarn.lock
            # if you have a Node server, include it (uncomment the next line):
            # server.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7C0B371A68E942079045EA778F6C13AD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ECF7485060544A748758726E6DD95EA8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C9311B13B5C14DC6A063F5564177D972 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'almuhammadi'
          slot-name: 'Production'
          package: .
