deploy:
  runs-on: ubuntu-latest
  needs: build
  permissions:
    id-token: write
    contents: read
  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B603D7ABEDF42A0A82B5567AA75DFE4 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_15E5B0CD31974BC7988720685E89BFBB }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08E969811A0C42C6A818E38DA304806C }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'almuhammadi'   # <-- use your new app name here
        slot-name: 'Production'
        package: .
