name: Build and deploy Node.js app to Azure Web App - almuhammadi

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies (Yarn)
        run: yarn install --frozen-lockfile || yarn install

      # Build CRA without failing on warnings
      - name: Build web client
        env:
          CI: false
          ESLINT_NO_DEV_ERRORS: true
        run: yarn build

      # Upload only what's needed at runtime
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            build
            src
            package.json
            yarn.lock
            # include any other server-side files if you have them:
            # server.js
            # tsconfig.json
            # .env.production

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'almuhammadi'
          slot-name: 'Production'
          package: .
